### ISSUE TITLE
Objective-C: unable to run build on simulator

### ISSUE THREAD

**Issue by dzmiquido** [qubitdigital/qubit-sdk-ios#19]
Environment
Xcode 11, Qubit iOS SDK 1.0.8
Customer is importing the SDK directly using Frameworks (e.g. not via CocoaPods)
Language: objective-C
Issue
Unable to build & run for the simulator in Xcode 11
Xcode11 declares QubitSDK as `undeclared identifier`
When run on device, the SDK seems to work
Device is iPhone SE (2nd gen) 
When importing into Swift code, seems to work fine

**Comment by hporter** [comment]
Fixed in #22
