### ISSUE TITLE
Xcode 10 issue

### ISSUE THREAD

**Issue by dejankrstevski89** [qubitdigital/qubit-sdk-ios#3]
Apple now exposes CommonCrypto to Swift natively, it seems that the CommonCrypto included in Qubit would cause a duplicate mapping.
```
module CommonCrypto [system] {
    header "/usr/include/CommonCrypto/CommonCrypto.h"
    export *
}
```
 Removing the CommonCrypto include folder from Qubit would then fix the Xcode 10 issue.

**Comment by alexolivier** [comment]
This has been released - thanks for raising @dejankrstevski89
